export const Users = {
  items: [
    {
      avatar_url: 'https://avatars.githubusercontent.com/u/1668?v=4',
      events_url: 'https://api.github.com/users/john/events{/privacy}',
      followers_url: 'https://api.github.com/users/john/followers',
      following_url: 'https://api.github.com/users/john/following{/other_user}',
      gists_url: 'https://api.github.com/users/john/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/john',
      id: 1668,
      login: 'john',
      node_id: 'MDQ6VXNlcjE2Njg=',
      organizations_url: 'https://api.github.com/users/john/orgs',
      received_events_url: 'https://api.github.com/users/john/received_events',
      repos_url: 'https://api.github.com/users/john/repos',
      score: 1,
      site_admin: false,
      starred_url: 'https://api.github.com/users/john/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/john/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/john',
    },
    {
      avatar_url: 'https://avatars.githubusercontent.com/u/1202528?v=4',
      events_url: 'https://api.github.com/users/johnpapa/events{/privacy}',
      followers_url: 'https://api.github.com/users/johnpapa/followers',
      following_url: 'https://api.github.com/users/johnpapa/following{/other_user}',
      gists_url: 'https://api.github.com/users/johnpapa/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/johnpapa',
      id: 1202528,
      login: 'johnpapa',
      node_id: 'MDQ6VXNlcjEyMDI1Mjg=',
      organizations_url: 'https://api.github.com/users/johnpapa/orgs',
      received_events_url: 'https://api.github.com/users/johnpapa/received_events',
      repos_url: 'https://api.github.com/users/johnpapa/repos',
      score: 1,
      site_admin: false,
      starred_url: 'https://api.github.com/users/johnpapa/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/johnpapa/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/johnpapa',
    },
    {
      avatar_url: 'https://avatars.githubusercontent.com/u/42133389?v=4',
      events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
      followers_url: 'https://api.github.com/users/john-smilga/followers',
      following_url: 'https://api.github.com/users/john-smilga/following{/other_user}',
      gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/john-smilga',
      id: 42133389,
      login: 'john-smilga',
      node_id: 'MDQ6VXNlcjQyMTMzMzg5',
      organizations_url: 'https://api.github.com/users/john-smilga/orgs',
      received_events_url: 'https://api.github.com/users/john-smilga/received_events',
      repos_url: 'https://api.github.com/users/john-smilga/repos',
      score: 1,
      site_admin: false,
      starred_url: 'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/john-smilga',
    },
    {
      avatar_url: 'https://avatars.githubusercontent.com/u/2466701?v=4',
      events_url: 'https://api.github.com/users/JohnSundell/events{/privacy}',
      followers_url: 'https://api.github.com/users/JohnSundell/followers',
      following_url: 'https://api.github.com/users/JohnSundell/following{/other_user}',
      gists_url: 'https://api.github.com/users/JohnSundell/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/JohnSundell',
      id: 2466701,
      login: 'JohnSundell',
      node_id: 'MDQ6VXNlcjI0NjY3MDE=',
      organizations_url: 'https://api.github.com/users/JohnSundell/orgs',
      received_events_url: 'https://api.github.com/users/JohnSundell/received_events',
      repos_url: 'https://api.github.com/users/JohnSundell/repos',
      score: 1,
      site_admin: false,
      starred_url: 'https://api.github.com/users/JohnSundell/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/JohnSundell/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/JohnSundell',
    },
    {
      avatar_url: 'https://avatars.githubusercontent.com/u/289994?v=4',
      events_url: 'https://api.github.com/users/johndpope/events{/privacy}',
      followers_url: 'https://api.github.com/users/johndpope/followers',
      following_url: 'https://api.github.com/users/johndpope/following{/other_user}',
      gists_url: 'https://api.github.com/users/johndpope/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/johndpope',
      id: 289994,
      login: 'johndpope',
      node_id: 'MDQ6VXNlcjI4OTk5NA==',
      organizations_url: 'https://api.github.com/users/johndpope/orgs',
      received_events_url: 'https://api.github.com/users/johndpope/received_events',
      repos_url: 'https://api.github.com/users/johndpope/repos',
      score: 1,
      site_admin: false,
      starred_url: 'https://api.github.com/users/johndpope/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/johndpope/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/johndpope',
    },
    {
      avatar_url: 'https://avatars.githubusercontent.com/u/22064?v=4',
      events_url: 'https://api.github.com/users/johnmyleswhite/events{/privacy}',
      followers_url: 'https://api.github.com/users/johnmyleswhite/followers',
      following_url: 'https://api.github.com/users/johnmyleswhite/following{/other_user}',
      gists_url: 'https://api.github.com/users/johnmyleswhite/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/johnmyleswhite',
      id: 22064,
      login: 'johnmyleswhite',
      node_id: 'MDQ6VXNlcjIyMDY0',
      organizations_url: 'https://api.github.com/users/johnmyleswhite/orgs',
      received_events_url: 'https://api.github.com/users/johnmyleswhite/received_events',
      repos_url: 'https://api.github.com/users/johnmyleswhite/repos',
      score: 1,
      site_admin: false,
      starred_url: 'https://api.github.com/users/johnmyleswhite/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/johnmyleswhite/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/johnmyleswhite',
    },
  ],
};
